---
title: "Mapa Interactivo"
--- 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,  fig.align="center", out.extra = 'style="display:block; margin:auto;"')
```

<div class=text-justify>

<br/>
<br/>

# Mapa Digital de Unidades Económicas que Generan Sustancias Contaminantes

Se muestra a continuación, una primera versión del mapa digital, cuyos puntos aún deben ser validados para garantizar su plena correspondencia con la ubicación geográfica de las unidades económicas.


```{r mapaleaflet1, echo=FALSE, message=FALSE, warning=FALSE, fig.height=6, cache =FALSE, out.width = "100%"}

library(sp)
library(rgdal)
library(leaflet)
library(htmltools)
library(htmlwidgets)
library(leaflet.extras)
library(mapview)  
library(raster)
library(bitops)
library(rjson)
library(jsonlite)
library(stringr)

puntos <- read.csv("Versiones del RETC/RETC_2017/RETC_2017_modif2.csv", header = T)
emis <- read.csv("Versiones del RETC/RETC_2017/emisiones.csv", header = T, encoding = 'UTF-8')

emis$emision_aire <- ifelse(emis$AIRE > 0, paste("Emitió al aire", emis$AIRE, "kg de", emis$SUSTANCIA, sep = ' '),'')
emis$emision_agua <- ifelse(emis$AGUA > 0, paste("Descargó en aguas", emis$AGUA, "kg de", emis$SUSTANCIA, sep = ' '),'')
emis$emision_suelo <- ifelse(emis$SUELO > 0, paste("Descargó en suelos", emis$SUELO, "kg de", emis$SUSTANCIA, sep = ' '),'')
emis$emision_reut <- ifelse(emis$REUTILIZACION > 0, paste("Reutilizó", emis$REUTILIZACION, "kg de", emis$SUSTANCIA, sep = ' '),'')
emis$emision_recic <- ifelse(emis$RECICLADO > 0, paste("Recicló", emis$RECICLADO, "kg de", emis$SUSTANCIA, sep = ' '),'')
emis$emision_copr <- ifelse(emis$COPROCESAMIENTO > 0, paste("Hizo coprocesamiento de", emis$COPROCESAMIENTO, "kg de", emis$SUSTANCIA, sep = ' '),'')
emis$emision_trat <- ifelse(emis$TRATAMIENTO > 0, paste("Dio tratamiento a", emis$TRATAMIENTO, "kg de", emis$SUSTANCIA, sep = ' '),'')
emis$emision_disp <- ifelse(emis$DISP_FINAL > 0, paste("Envió a disposición final", emis$DISP_FINAL, "kg de", emis$SUSTANCIA, sep = ' '),'')
emis$emision_alcant <- ifelse(emis$ALCANTARILLADO > 0, paste("Vertió al alcantarillado", emis$ALCANTARILLADO, "kg de", emis$SUSTANCIA, sep = ' '),'')
emis$emision_incin <- ifelse(emis$INCINERACION > 0, paste("Incineró", emis$INCINERACION, "kg de", emis$SUSTANCIA, sep = ' '),'')
emis$emision_otro <- ifelse(emis$OTROS > 0, paste("Dio otro tratamiento a", emis$OTROS, "kg de", emis$SUSTANCIA, sep = ' '),'')
emis$emisiones <- paste(emis$emision_aire, emis$emision_agua, emis$emision_suelo, emis$emision_reut, emis$emision_recic, 
                        emis$emision_copr, emis$emision_trat, emis$emision_disp, emis$emision_alcant,
                        emis$emision_incin, emis$emision_otro, sep = ' ')
emistot <- tapply(emis$emisiones, emis$NRA, paste)
cop <- tapply(emis$Comp_or_persist, emis$NRA, sum, na.rm = T)
gei <- tapply(emis$Gases_Efecto_Invern, emis$NRA, sum, na.rm = T)
haral <- tapply(emis$Hidrocarb_arom_y_alif, emis$NRA, sum, na.rm = T)
met <- tapply(emis$Metales, emis$NRA, sum, na.rm = T)
orghal <- tapply(emis$Organohalogenados, emis$NRA, sum, na.rm = T)
saozo <- tapply(emis$Sust_agot_del_ozono, emis$NRA, sum, na.rm = T)
otrsp <- tapply(emis$Otras_sust_peligr, emis$NRA, sum, na.rm = T)
plag <- tapply(emis$Plaguicidas, emis$NRA, sum, na.rm = T)


emis$cop_kg <- rep(0, dim(emis)[1])
emis$cop_kg[which(emis$GRUPO == "Compuestos Organicos Persistentes")] <- rowSums(emis[which(emis$GRUPO == "Compuestos Organicos Persistentes"),8:18])
emis$gei_kg <- rep(0, dim(emis)[1])
emis$gei_kg[which(emis$GRUPO == "Gases de Efecto Invernadero")] <- rowSums(emis[which(emis$GRUPO == "Gases de Efecto Invernadero"),8:18])
emis$haral_kg <- rep(0, dim(emis)[1])
emis$haral_kg[which(emis$GRUPO == "Hidrocarburos Aromaticos y Alifaticos")] <- rowSums(emis[which(emis$GRUPO == "Hidrocarburos Aromaticos y Alifaticos"),8:18])
emis$met_kg <- rep(0, dim(emis)[1])
emis$met_kg[which(emis$GRUPO == "Metales")] <- rowSums(emis[which(emis$GRUPO == "Metales"),8:18])
emis$orghal_kg <- rep(0, dim(emis)[1])
emis$orghal_kg[which(emis$GRUPO == "Organohalogenados")] <- rowSums(emis[which(emis$GRUPO == "Organohalogenados"),8:18])
emis$saozo_kg <- rep(0, dim(emis)[1])
emis$saozo_kg[which(emis$GRUPO == "Sustancias Agotadoras de la Capa de Ozono")] <- rowSums(emis[which(emis$GRUPO == "Sustancias Agotadoras de la Capa de Ozono"),8:18])
emis$otrsp_kg <- rep(0, dim(emis)[1])
emis$otrsp_kg[which(emis$GRUPO == "Otras sustancias")] <- rowSums(emis[which(emis$GRUPO == "Otras sustancias"),8:18])
emis$plag_kg <- rep(0, dim(emis)[1])
emis$plag_kg[which(emis$GRUPO == "Plaguicidas")] <- rowSums(emis[which(emis$GRUPO == "Plaguicidas"),8:18])

copkg <- tapply(emis$cop_kg, emis$NRA, sum)
rad_copkg <- ifelse(copkg == max(copkg), 2*log(copkg)**2, 0)
geikg <- tapply(emis$gei_kg, emis$NRA, sum)
rad_geikg <- ifelse(geikg > 0, 10*log(geikg), 0)
haralkg <- tapply(emis$haral_kg, emis$NRA, sum)
rad_haralkg <- ifelse(haralkg > 0, 10*log(haralkg), 0)
metkg <- tapply(emis$met_kg, emis$NRA, sum)
rad_metkg <- ifelse(metkg > 0, 2*log(metkg)**2, 0)
orghalkg <- tapply(emis$orghal_kg, emis$NRA, sum)
rad_orghalkg <- ifelse(orghalkg > 0, 2*log(orghalkg)**2, 0)
saozokg <- tapply(emis$saozo_kg, emis$NRA, sum)
rad_saozokg <- ifelse(saozokg > 0, 2*log(saozokg)**2, 0)
otrspkg <- tapply(emis$otrsp_kg, emis$NRA, sum)
rad_otrspkg <- ifelse(otrspkg > 0, 2*log(otrspkg)**2, 0)
plagkg <- tapply(emis$plag_kg, emis$NRA, sum)
rad_plagkg <- ifelse(plagkg > 0, 2*log(plagkg)**2, 0)


NRA_valid <- unique(emis$NRA)
puntos2 <- puntos[which(is.element(puntos$NRA,NRA_valid)),]

aux <- cbind(as.data.frame(emistot),cop,gei,haral,met,orghal,saozo,otrsp,plag)
aux$emistot2 <- str_replace_all(aux$emistot, "^['c(']", "")


puntos_sp <- SpatialPointsDataFrame(puntos2[,c(20,15)],puntos2[,-c(20,15)])
writeOGR(puntos_sp, "shape_files", "puntos", driver="ESRI Shapefile", encoding = 'UTF-8',
         overwrite_layer=T)
puntos_sp2 <- readOGR("shape_files/puntos.shp", encoding = 'UTF-8',
                      "puntos", verbose=FALSE)
puntos_sp2@data$lat <- puntos2$lat
puntos_sp2@data$lon <- puntos2$lon

puntos_sp1 <- SpatialPointsDataFrame(puntos2[copkg > 0,c(20,15)],puntos2[copkg > 0,-c(20,15)])
writeOGR(puntos_sp1, "shape_files", "puntos1", driver="ESRI Shapefile", encoding = 'UTF-8',
         overwrite_layer=T)
puntos_sp12 <- readOGR("shape_files/puntos1.shp", encoding = 'UTF-8',
                      "puntos1", verbose=FALSE)
puntos_sp12@data$lat <- puntos2$lat[which(copkg > 0)]
puntos_sp12@data$lon <- puntos2$lon[which(copkg > 0)]

puntos_sp2 <- SpatialPointsDataFrame(puntos2[geikg > 0,c(20,15)],puntos2[geikg > 0,-c(20,15)])
writeOGR(puntos_sp2, "shape_files", "puntos2a", driver="ESRI Shapefile", encoding = 'UTF-8',
         overwrite_layer=T)
puntos_sp22 <- readOGR("shape_files/puntos2a.shp", encoding = 'UTF-8',
                       "puntos2a", verbose=FALSE)
puntos_sp22@data$lat <- puntos2$lat[which(geikg > 0)]
puntos_sp22@data$lon <- puntos2$lon[which(geikg > 0)]

puntos_sp3 <- SpatialPointsDataFrame(puntos2[haralkg > 0,c(20,15)],puntos2[haralkg > 0,-c(20,15)])
writeOGR(puntos_sp3, "shape_files", "puntos3", driver="ESRI Shapefile", encoding = 'UTF-8',
         overwrite_layer=T)
puntos_sp32 <- readOGR("shape_files/puntos3.shp", encoding = 'UTF-8',
                       "puntos3", verbose=FALSE)
puntos_sp32@data$lat <- puntos2$lat[which(haralkg > 0)]
puntos_sp32@data$lon <- puntos2$lon[which(haralkg > 0)]

puntos_sp4 <- SpatialPointsDataFrame(puntos2[metkg > 0,c(20,15)],puntos2[metkg > 0,-c(20,15)])
writeOGR(puntos_sp4, "shape_files", "puntos4", driver="ESRI Shapefile", encoding = 'UTF-8',
         overwrite_layer=T)
puntos_sp42 <- readOGR("shape_files/puntos4.shp", encoding = 'UTF-8',
                       "puntos4", verbose=FALSE)
puntos_sp42@data$lat <- puntos2$lat[which(metkg > 0)]
puntos_sp42@data$lon <- puntos2$lon[which(metkg > 0)]

puntos_sp5 <- SpatialPointsDataFrame(puntos2[orghalkg > 0,c(20,15)],puntos2[orghalkg > 0,-c(20,15)])
writeOGR(puntos_sp5, "shape_files", "puntos5", driver="ESRI Shapefile", encoding = 'UTF-8',
         overwrite_layer=T)
puntos_sp52 <- readOGR("shape_files/puntos5.shp", encoding = 'UTF-8',
                       "puntos5", verbose=FALSE)
puntos_sp52@data$lat <- puntos2$lat[which(orghalkg > 0)]
puntos_sp52@data$lon <- puntos2$lon[which(orghalkg > 0)]

puntos_sp6 <- SpatialPointsDataFrame(puntos2[saozokg > 0,c(20,15)],puntos2[saozokg > 0,-c(20,15)])
writeOGR(puntos_sp6, "shape_files", "puntos6", driver="ESRI Shapefile", encoding = 'UTF-8',
         overwrite_layer=T)
puntos_sp62 <- readOGR("shape_files/puntos6.shp", encoding = 'UTF-8',
                       "puntos6", verbose=FALSE)
puntos_sp62@data$lat <- puntos2$lat[which(saozokg > 0)]
puntos_sp62@data$lon <- puntos2$lon[which(saozokg > 0)]

puntos_sp7 <- SpatialPointsDataFrame(puntos2[otrspkg > 0,c(20,15)],puntos2[otrspkg > 0,-c(20,15)])
writeOGR(puntos_sp7, "shape_files", "puntos7", driver="ESRI Shapefile", encoding = 'UTF-8',
         overwrite_layer=T)
puntos_sp72 <- readOGR("shape_files/puntos7.shp", encoding = 'UTF-8',
                       "puntos7", verbose=FALSE)
puntos_sp72@data$lat <- puntos2$lat[which(otrspkg > 0)]
puntos_sp72@data$lon <- puntos2$lon[which(otrspkg > 0)]

puntos_sp8 <- SpatialPointsDataFrame(puntos2[plagkg > 0,c(20,15)],puntos2[plagkg > 0,-c(20,15)])
writeOGR(puntos_sp8, "shape_files", "puntos8", driver="ESRI Shapefile", encoding = 'UTF-8',
         overwrite_layer=T)
puntos_sp82 <- readOGR("shape_files/puntos8.shp", encoding = 'UTF-8',
                       "puntos8", verbose=FALSE)
puntos_sp82@data$lat <- puntos2$lat[which(plagkg > 0)]
puntos_sp82@data$lon <- puntos2$lon[which(plagkg > 0)]

                                    
iconos <- iconList(
  cop_icon = makeIcon("imag/organ.png", 28, 28),
  gei_icon = makeIcon("imag/gei.png", 28, 28),
  gei_icon = makeIcon("imag/haral.png", 28, 28),
  gei_icon = makeIcon("imag/met.png", 28, 28),
  gei_icon = makeIcon("imag/orghal.png", 28, 28),
  gei_icon = makeIcon("imag/saozo.png", 28, 28),
  gei_icon = makeIcon("imag/otrsp.jpg", 28, 28),
  gei_icon = makeIcon("imag/plag.png", 28, 28))


m <- leaflet() %>% addTiles() %>% addFullscreenControl()
m %>% setView(lng = -102.43, lat = 22.37, zoom = 5.4)  %>%
  addMarkers(data=puntos_sp12, icon = iconos[1],
             clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = T),
             popup = paste0( "<strong>NRA: </strong>", puntos2$NRA[which(copkg > 0)], "</br>",
                             "<strong>MUNICIPIO: </strong>", paste(puntos2$MUNICIPIO[which(copkg > 0)], puntos2$ESTADO[which(copkg > 0)],sep = ", "), "</br>",
                             "<strong>NOMBRE_ESTABLECIMIENTO: </strong>", puntos2$NOMBRE[which(copkg > 0)], "</br>",
                             "<strong>TIPO DE INDUSTRIA: </strong>", puntos2$SECTOR[which(copkg > 0)], "</br>",
                             "<strong>GIRO: </strong>", puntos2$DESC_SCIAN[which(copkg > 0)], "</br>",
                             "<strong>ACTIVIDAD: </strong>", puntos2$ACTIVIDAD[which(copkg > 0)], "</br>",
                             "<strong>EMISIONES: </strong>", aux$emistot2[which(copkg > 0)]),
             group = "Compuestos Orgánicos Persistentes")  %>%
  addMarkers(data=puntos_sp22, icon = iconos[2],
             clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = T),
             popup = paste0( "<strong>NRA: </strong>", puntos2$NRA[which(geikg > 0)], "</br>",
                             "<strong>MUNICIPIO: </strong>", paste(puntos2$MUNICIPIO[which(geikg > 0)],puntos2$ESTADO[which(geikg > 0)],sep = ", "), "</br>",
                             "<strong>NOMBRE_ESTABLECIMIENTO: </strong>", puntos2$NOMBRE[which(geikg > 0)], "</br>",
                             "<strong>TIPO DE INDUSTRIA: </strong>", puntos2$SECTOR[which(geikg > 0)], "</br>",
                             "<strong>GIRO: </strong>", puntos2$DESC_SCIAN[which(geikg > 0)], "</br>",
                             "<strong>ACTIVIDAD: </strong>", puntos2$ACTIVIDAD[which(geikg > 0)], "</br>",
                             "<strong>EMISIONES: </strong>", aux$emistot2[which(geikg > 0)]),
             group = "Gases de Efecto Invernadero")  %>%
  addMarkers(data=puntos_sp32, icon = iconos[3],
             clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = T),
             popup = paste0( "<strong>NRA: </strong>", puntos2$NRA[which(haralkg > 0)], "</br>",
                             "<strong>MUNICIPIO: </strong>", paste(puntos2$MUNICIPIO[which(haralkg > 0)],puntos2$ESTADO[which(haralkg > 0)],sep = ", "), "</br>",
                             "<strong>NOMBRE_ESTABLECIMIENTO: </strong>", puntos2$NOMBRE[which(haralkg > 0)], "</br>",
                             "<strong>TIPO DE INDUSTRIA: </strong>", puntos2$SECTOR[which(haralkg > 0)], "</br>",
                             "<strong>GIRO: </strong>", puntos2$DESC_SCIAN[which(haralkg > 0)], "</br>",
                             "<strong>ACTIVIDAD: </strong>", puntos2$ACTIVIDAD[which(haralkg > 0)], "</br>",
                             "<strong>EMISIONES: </strong>", aux$emistot2[which(haralkg > 0)]),
             group = "Hidrocarburos Aromáticos y Alifáticos")  %>%
  addMarkers(data=puntos_sp42, icon = iconos[4],
             clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = T),
             popup = paste0( "<strong>NRA: </strong>", puntos2$NRA[which(metkg > 0)], "</br>",
                             "<strong>MUNICIPIO: </strong>", paste(puntos2$MUNICIPIO[which(metkg > 0)],puntos2$ESTADO[which(metkg > 0)],sep = ", "), "</br>",
                             "<strong>NOMBRE_ESTABLECIMIENTO: </strong>", puntos2$NOMBRE[which(metkg > 0)], "</br>",
                             "<strong>TIPO DE INDUSTRIA: </strong>", puntos2$SECTOR[which(metkg > 0)], "</br>",
                             "<strong>GIRO: </strong>", puntos2$DESC_SCIAN[which(metkg > 0)], "</br>",
                             "<strong>ACTIVIDAD: </strong>", puntos2$ACTIVIDAD[which(metkg > 0)], "</br>",
                             "<strong>EMISIONES: </strong>", aux$emistot2[which(metkg > 0)]),
             group = "Metales")  %>%
  addMarkers(data=puntos_sp52, icon = iconos[5],
             clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = T),
             popup = paste0( "<strong>NRA: </strong>", puntos2$NRA[which(orghalkg > 0)], "</br>",
                             "<strong>MUNICIPIO: </strong>", paste(puntos2$MUNICIPIO[which(orghalkg > 0)],puntos2$ESTADO[which(orghalkg > 0)],sep = ", "), "</br>",
                             "<strong>NOMBRE_ESTABLECIMIENTO: </strong>", puntos2$NOMBRE[which(orghalkg > 0)], "</br>",
                             "<strong>TIPO DE INDUSTRIA: </strong>", puntos2$SECTOR[which(orghalkg > 0)], "</br>",
                             "<strong>GIRO: </strong>", puntos2$DESC_SCIAN[which(orghalkg > 0)], "</br>",
                             "<strong>ACTIVIDAD: </strong>", puntos2$ACTIVIDAD[which(orghalkg > 0)], "</br>",
                             "<strong>EMISIONES: </strong>", aux$emistot2[which(orghalkg > 0)]),
             group = "Organohalogenados")  %>%
  addMarkers(data=puntos_sp62, icon = iconos[6],
             clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = T),
             popup = paste0( "<strong>NRA: </strong>", puntos2$NRA[which(saozokg > 0)], "</br>",
                             "<strong>MUNICIPIO: </strong>", paste(puntos2$MUNICIPIO[which(saozokg > 0)],puntos2$ESTADO[which(saozokg > 0)],sep = ", "), "</br>",
                             "<strong>NOMBRE_ESTABLECIMIENTO: </strong>", puntos2$NOMBRE[which(saozokg > 0)], "</br>",
                             "<strong>TIPO DE INDUSTRIA: </strong>", puntos2$SECTOR[which(saozokg > 0)], "</br>",
                             "<strong>GIRO: </strong>", puntos2$DESC_SCIAN[which(saozokg > 0)], "</br>",
                             "<strong>ACTIVIDAD: </strong>", puntos2$ACTIVIDAD[which(saozokg > 0)], "</br>",
                             "<strong>EMISIONES: </strong>", aux$emistot2[which(saozokg > 0)]),
             group = "Sustancias Agotadoras de la Capa de Ozono")  %>%
  addMarkers(data=puntos_sp72, icon = iconos[7],
             clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = T),
             popup = paste0( "<strong>NRA: </strong>", puntos2$NRA[which(otrspkg > 0)], "</br>",
                             "<strong>MUNICIPIO: </strong>", paste(puntos2$MUNICIPIO[which(otrspkg > 0)],puntos2$ESTADO[which(otrspkg > 0)],sep = ", "), "</br>",
                             "<strong>NOMBRE_ESTABLECIMIENTO: </strong>", puntos2$NOMBRE[which(otrspkg > 0)], "</br>",
                             "<strong>TIPO DE INDUSTRIA: </strong>", puntos2$SECTOR[which(otrspkg > 0)], "</br>",
                             "<strong>GIRO: </strong>", puntos2$DESC_SCIAN[which(otrspkg > 0)], "</br>",
                             "<strong>ACTIVIDAD: </strong>", puntos2$ACTIVIDAD[which(otrspkg > 0)], "</br>",
                             "<strong>EMISIONES: </strong>", aux$emistot2[which(otrspkg > 0)]),
             group = "Otras Sustancias Peligrosas")  %>%
  addMarkers(data=puntos_sp82, icon = iconos[8],
             clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = T),
             popup = paste0( "<strong>NRA: </strong>", puntos2$NRA[which(plagkg > 0)], "</br>",
                             "<strong>MUNICIPIO: </strong>", paste(puntos2$MUNICIPIO[which(plagkg > 0)],puntos2$ESTADO[which(plagkg > 0)],sep = ", "), "</br>",
                             "<strong>NOMBRE_ESTABLECIMIENTO: </strong>", puntos2$NOMBRE[which(plagkg > 0)], "</br>",
                             "<strong>TIPO DE INDUSTRIA: </strong>", puntos2$SECTOR[which(plagkg > 0)], "</br>",
                             "<strong>GIRO: </strong>", puntos2$DESC_SCIAN[which(plagkg > 0)], "</br>",
                             "<strong>ACTIVIDAD: </strong>", puntos2$ACTIVIDAD[which(plagkg > 0)], "</br>",
                             "<strong>EMISIONES: </strong>", aux$emistot2[which(plagkg > 0)]),
             group = "Plaguicidas")  %>%
  addCircles(puntos_sp12$lon, puntos_sp12$lat, weight=1, radius = rad_copkg[which(copkg > 0)], color= "cyan4", 
             group = "Compuestos Orgánicos Persistentes") %>% 
  addCircles(puntos_sp22$lon, puntos_sp22$lat, weight=1, radius = rad_geikg[which(geikg > 0)], color= "cornflowerblue", 
             group = "Gases de Efecto Invernadero") %>%
  addCircles(puntos_sp32$lon, puntos_sp32$lat, weight=1, radius = rad_haralkg[which(haralkg > 0)], color= "chartreuse4", 
             group = "Hidrocarburos Aromáticos y Alifáticos") %>%  
  addCircles(puntos_sp42$lon, puntos_sp42$lat, weight=1, radius = rad_metkg[which(metkg > 0)], color= "chocolate3", 
             group = "Metales") %>% 
  addCircles(puntos_sp52$lon, puntos_sp52$lat, weight=1, radius = rad_orghalkg[which(orghalkg > 0)], color= "chocolate1", 
             group = "Organohalogenados") %>%  
  addCircles(puntos_sp62$lon, puntos_sp62$lat, weight=1, radius = rad_saozokg[which(saozokg > 0)], color= "blueviolet", 
             group = "Sustancias Agotadoras de la Capa de Ozono") %>%
  addCircles(puntos_sp72$lon, puntos_sp72$lat, weight=1, radius = rad_otrspkg[which(otrspkg > 0)], color= "brown", 
             group = "Otras Sustancias Peligrosas") %>%
  addCircles(puntos_sp82$lon, puntos_sp82$lat, weight=1, radius = rad_plagkg[which(plagkg > 0)], color= "aquamarine3", 
             group = "Plaguicidas") %>%
addLayersControl(overlayGroups = c("Compuestos Orgánicos Persistentes", "Gases de Efecto Invernadero", "Hidrocarburos Aromáticos y Alifáticos", 
                                          "Metales", "Organohalogenados", "Sustancias Agotadoras de la Capa de Ozono", "Otras Sustancias Peligrosas", 
                                          "Plaguicidas"), 
                        options = layersControlOptions(collapsed = T), position="topleft") %>% 
  addMeasure(
    position = "bottomleft",
    primaryLengthUnit = "meters",
    primaryAreaUnit = "sqmeters",
    activeColor = "#3D535D",
    completedColor = "#7D4479") %>%   
  addEasyButton(easyButton(
  icon="fa-crosshairs", 
  title="Ubícame",
  onClick=JS("function(btn, map){ map.locate({setView: true}); }")))  %>%
  addMouseCoordinates() %>%
  addHomeButton(extent(puntos_sp2), layer.name = "i",  position = "topleft")

```

</div>